# Generated by Django 5.0.6 on 2024-07-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название блога"),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Ссылка на блог"
                    ),
                ),
                ("content", models.TextField(verbose_name="Контент блога")),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
