# Generated by Django 5.0.6 on 2024-07-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
